import playfunction

piece = [
    #piece is Bad Apple!!
    #in 2-2 measure
     #=================bar 1=======================#
    ['Eb3','eighth'],
    ['Eb3','sixteenth'],
    ['E4','sixteenth'],
    ['rest','sixteenth'],
    ['E4','sixteenth'],
    ['D4','sixteenth'],
    ['E4','sixteenth'],
    ['Eb3','eighth'],
    ['Eb3','sixteenth'],
    ['E4','sixteenth'],
    ['rest','sixteenth'],
    ['E4','sixteenth'],
    ['D4','sixteenth'],
    ['E4','sixteenth'],
     #=================bar 2=======================#
    ['Eb3','eighth'],
    ['Eb3','sixteenth'],
    ['E4','sixteenth'],
    ['rest','sixteenth'],
    ['E4','sixteenth'],
    ['D4','sixteenth'],
    ['E4','sixteenth'],
    ['Gb4','eighth'],
    ['E4','sixteenth'],
    ['Fb4','sixteenth'],
    ['Gb4','eighth'],
    ['Fb4','sixteenth'],
    ['Ab4','sixteenth'],
     #=================bar 3=======================#
    ['Eb3','eighth'],
    ['Eb3','sixteenth'],
    ['E4','sixteenth'],
    ['rest','sixteenth'],
    ['E4','sixteenth'],
    ['D4','sixteenth'],
    ['E4','sixteenth'],
    ['Eb3','eighth'],
    ['Eb3','sixteenth'],
    ['E4','sixteenth'],
    ['rest','sixteenth'],
    ['E4','sixteenth'],
    ['D4','sixteenth'],
    ['E4','sixteenth'],
     #=================bar 4=======================#
    ['Eb3','eighth'],
    ['Eb3','sixteenth'],
    ['E4','sixteenth'],
    ['rest','sixteenth'],
    ['E4','sixteenth'],
    ['D4','sixteenth'],
    ['E4','sixteenth'],
    ['Ab4','eighth'],
    ['Gb4','sixteenth'],
    ['Ab4','sixteenth'],
    ['Gb4','eighth'],
    ['E4','sixteenth'],
    ['Gb4','sixteenth'],
     #=================bar 5=======================#
    ['Eb3','eighth'],
    ['Eb3','sixteenth'],
    ['E4','sixteenth'],
    ['rest','sixteenth'],
    ['E4','sixteenth'],
    ['D4','sixteenth'],
    ['E4','sixteenth'],
    ['Eb3','eighth'],
    ['Eb3','sixteenth'],
    ['E4','sixteenth'],
    ['rest','sixteenth'],
    ['E4','sixteenth'],
    ['D4','sixteenth'],
    ['E4','sixteenth'],
     #=================bar 6=======================#
    ['Eb3','eighth'],
    ['Eb3','sixteenth'],
    ['E4','sixteenth'],
    ['rest','sixteenth'],
    ['E4','sixteenth'],
    ['D4','sixteenth'],
    ['E4','sixteenth'],
    ['Gb4','eighth'],
    ['E4','sixteenth'],
    ['Fb4','sixteenth'],
    ['Gb4','eighth'],
    ['Fb4','sixteenth'],
    ['Ab4','sixteenth'],
     #=================bar 7=======================#
    ['Eb3','eighth'],
    ['Eb3','sixteenth'],
    ['E4','sixteenth'],
    ['rest','sixteenth'],
    ['E4','sixteenth'],
    ['D4','sixteenth'],
    ['E4','sixteenth'],
    ['Eb3','eighth'],
    ['Eb3','sixteenth'],
    ['E4','sixteenth'],
    ['rest','sixteenth'],
    ['E4','sixteenth'],
    ['D4','sixteenth'],
    ['E4','sixteenth'],
     #=================bar 8=======================#
    ['Eb3','eighth'],
    ['Eb3','sixteenth'],
    ['E4','sixteenth'],
    ['rest','sixteenth'],
    ['E4','sixteenth'],
    ['D4','sixteenth'],
    ['E4','sixteenth'],
    ['Ab4','eighth'],
    ['Gb4','eighth'],
    ['Ab4','eighth'],
    ['Gb4','eighth'],
    ['E4','eighth'],
    ['G4','eighth'],

    #=================bar 9=======================#
    ['E4','eighth'],
    ['F4','eighth'],
    ['Gb4','eighth'],
    ['Ab4','eighth'],
    ['Bb4','qtr'],
    ['B3','eighth'],
    ['Eb5','eighth'],
    ['Db5','eighth'],

     #=================bar 10=======================#
    ['Bb4','qtr'],
    ['E4','qtr'],
    ['Bb4','eighth'],
    ['Ab4','eighth'],
    ['Gb4','eighth'],
    ['Fb4','eighth'],
    
    #=================bar 11=======================#
    ['E4','eighth'],
    ['F4','eighth'],
    ['Gb4','eighth'],
    ['Ab4','eighth'],
    ['Bb4','qtr'],
    ['B3','eighth'],
    ['Eb5','eighth'],
    ['Db5','eighth'],

    #=================bar 11=======================#
    ['E4','eighth'],
    ['F4','eighth'],
    ['Gb4','eighth'],
    ['Ab4','eighth'],
    ['B3','eighth'],
    ['Eb5','eighth'],
    ['Db5','eighth'],


]

playfunction.playSong(piece,60)


